theme: jekyll-theme-cayman
title: s3736964's World of Information Technology
description: My name is Sarah Bylmakers, I am 19 years old and I am from Sydney, Australia. I completed my NSW HSC in the end of 2017 and am now studying a Bachelor of Information Technology at RMIT, Melbourne city campus.
             I moved to Melbourne (and into the cheapest possible apartment available) by myself in the beginning of July, 2018.  
