theme: jekyll-theme-cayman
title: My Profile: Sarah Bylmakers

description: My name is Sarah Bylmakers, I am 19 years old and I am from Sydney, Australia. I completed my NSW HSC in the end of 2017 and am now studying a Bachelor of Information Technology at RMIT's Melbourne City Campus. I am originally from Sydney, as I moved to Melbourne (and into the cheapest possible apartment) in the beginning of July, 2018.
